# Generated by Django 4.1.7 on 2023-04-03 10:07

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=32, verbose_name='companyName')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=128, verbose_name='taskName')),
                ('taskDescription', models.CharField(max_length=1024, verbose_name='taskDescription')),
            ],
        ),
    ]
