# Generated by Django 4.1.7 on 2023-04-03 10:07

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('channelName', models.CharField(max_length=32, verbose_name='channelName')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('channelType', models.CharField(choices=[('0', 'CHAT'), ('1', 'VOICE')], default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('messageBody', models.CharField(max_length=3096, verbose_name='messageBody')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('repliedFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
