# Generated by Django 4.1.7 on 2023-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channelType',
            field=models.CharField(choices=[('0', 'CHAT'), ('1', 'VOICE')], default='0', max_length=10),
        ),
    ]
